version: '3'

services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=m_fit
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    external: true
